all:
	(cd common; make)
	(cd transform; make)
	(cd algorithm; make)
	(cd workflow; make)
	(cd tools; make)

clean:
	(cd common; make clean)
	(cd transform; make clean)
	(cd tools; make clean)
	(cd algorithm; make clean)
	(cd workflow; make clean)
